export const blogArchivYamlSnapshot = `
- navigation:
  - list:
    - listitem:
      - link "Home"
    - listitem:
      - link "Blog"
    - listitem:
      - link "Tags"
  - button "Change color scheme":
    - img
- main:
  - heading "Blog Archive" [level=1]
  - link /Like Ed Sheeran with 4 chords - Efficient keybindings chords for your system February \\d+, \\d+ \\(Updated on March \\d+, \\d+ \\) \\.\\.\\. Read Post/:
    - heading "Like Ed Sheeran with 4 chords - Efficient keybindings chords for your system" [level=2]
    - time: /February \\d+, \\d+/
    - time: /March \\d+, \\d+/
    - img
  - 'link /The never type in TypeScript February \\d+, \\d+ \\(Updated on March \\d+, \\d+ \\) The greatly underestimated and often overlooked never type is a core Type in the TypeScript type hierarchy\\. TypeScript itself says: "The never type represents the type of values that never occur\\." Even though it is said to never appear, it is omnipresent\\. Read Post/':
    - heading "The never type in TypeScript" [level=2]
    - time: /February \\d+, \\d+/
    - time: /March \\d+, \\d+/
    - img
  - navigation "Pagination": Page 1 of 1
- contentinfo:
  - link "Contact"
  - link "Imprint"
  - link "Privacy"
  - link "Twitter"
  - link "Github"
  - link "LinkedIn"
  - link "XING"
  - paragraph: /© \\d+ honey\\.glass\\. All rights reserved\\./
`;
